FROM php:5-apache
WORKDIR /var/www/html

RUN apt-get update
RUN apt-get -y install wget libpcre3-dev libmcrypt-dev libfreetype6-dev libjpeg62-turbo-dev libjpeg-dev libmagickwand-dev
RUN rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install gd mcrypt pdo pdo_mysql mysql mbstring

RUN a2enmod rewrite && a2enmod headers && a2enmod ssl && a2enmod actions

COPY web2 /src
RUN rm -rf /var/www/html && mv /src /var/www/html &&\
    chmod -R 777 /var/www/html/images /var/www/html/img

CMD apache2-foreground