FROM nginx:alpine
COPY engin1/conf/nginx.conf /etc/nginx/conf/nginx.conf
COPY engin1/conf.d /etc/nginx/conf.d
COPY engin1/assets/static /var/www/assets/static
COPY engin1/assets/log /var/www/assets/log