#!/usr/bin/expect -f

#exp_internal 1

set timeout -1

set filename [lindex $argv 0]
set userealm [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]

#puts "filename: $filename"
#puts "userealm: $userealm"
#puts "username: $username"
#puts "password: $password"

spawn htdigest -c $filename $userealm $username
expect "password:"
send "$password\r"
expect "password:"
send "$password\r"
expect "#"

exit
